services:
    lapchess-client:
        container_name: lapchess-client
        volumes:
            - ./:/app
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - 3000:3000
