services:
    lapchess-server:
        container_name: lapchess-server
        volumes:
            - ./:/app
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - 4000:4000
