export { default as bishopMoves } from './Bishop'
export { default as rookMoves } from './Rook'
export { default as kingMoves } from './King'
export { default as pawnMoves } from './Pawn'
export { default as knightMoves } from './Knight'
export { default as queenMoves } from './Queen'
