export { default as createGameQuery } from './createGameQuery'
export { default as deleteGameQuery } from './deleteGameQuery'
export { default as fetchGameQuery } from './fetchGameQuery'
export { default as updateGameQuery } from './updateGame/updateGameQuery'
export { default as resignGameQuery } from './updateGame/resignGameQuery'
export { default as restartGameQuery } from './updateGame/restartGameQuery'
export { default as cancelGameQuery } from './updateGame/cancelGameQuery'
export { default as drawGameQuery } from './updateGame/drawGameQuery'
