export { default as Cells } from './static/Cells'
export { default as NextMoves } from './dynamic/NextMoves'
export { default as CheckStatus } from './dynamic/CheckStatus'
export { default as Promotion } from './dynamic/Promotion'
export { default as GameOver } from './dynamic/GameOver/GameOver'
export { default as Pieces } from './dynamic/Pieces/Pieces'
